// Generated by fbsgen from p/ds/prk/p4
export var p4;
(function (p4_1) {
    function P4D1$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P4D1$$new = P4D1$$new;
    function P4D4$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P4D4$$new = P4D4$$new;
    function P4D8$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P4D8$$new = P4D8$$new;
    function P4DD$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P4DD$$new = P4DD$$new;
    function P4DK$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P4DK$$new = P4DK$$new;
    function P4DS$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P4DS$$new = P4DS$$new;
    function P44441$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p4_1.P44441$$new = P44441$$new;
    function P44444$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p4_1.P44444$$new = P44444$$new;
    function P44448$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p4_1.P44448$$new = P44448$$new;
    function P4444D$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p4_1.P4444D$$new = P4444D$$new;
    function P4444K$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p4_1.P4444K$$new = P4444K$$new;
    function P4444S$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p4_1.P4444S$$new = P4444S$$new;
    function P481$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P481$$new = P481$$new;
    function P484$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P484$$new = P484$$new;
    function P488$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P488$$new = P488$$new;
    function P48D$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P48D$$new = P48D$$new;
    function P48K$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P48K$$new = P48K$$new;
    function P48S$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P48S$$new = P48S$$new;
    function P444441$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p4_1.P444441$$new = P444441$$new;
    function P444444$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p4_1.P444444$$new = P444444$$new;
    function P444448$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p4_1.P444448$$new = P444448$$new;
    function P44444D$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p4_1.P44444D$$new = P44444D$$new;
    function P44444K$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p4_1.P44444K$$new = P44444K$$new;
    function P44444S$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p4_1.P44444S$$new = P44444S$$new;
    function P441$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P441$$new = P441$$new;
    function P444$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P444$$new = P444$$new;
    function P448$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P448$$new = P448$$new;
    function P44D$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P44D$$new = P44D$$new;
    function P44K$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P44K$$new = P44K$$new;
    function P44S$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P44S$$new = P44S$$new;
    function P4K1$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P4K1$$new = P4K1$$new;
    function P4K4$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P4K4$$new = P4K4$$new;
    function P4K8$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P4K8$$new = P4K8$$new;
    function P4KD$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P4KD$$new = P4KD$$new;
    function P4KK$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P4KK$$new = P4KK$$new;
    function P4KS$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P4KS$$new = P4KS$$new;
    function P41$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    p4_1.P41$$new = P41$$new;
    function P44$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    p4_1.P44$$new = P44$$new;
    function P48$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    p4_1.P48$$new = P48$$new;
    function P4D$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    p4_1.P4D$$new = P4D$$new;
    function P4K$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    p4_1.P4K$$new = P4K$$new;
    function P4S$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    p4_1.P4S$$new = P4S$$new;
    function P411$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P411$$new = P411$$new;
    function P414$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P414$$new = P414$$new;
    function P418$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P418$$new = P418$$new;
    function P41D$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P41D$$new = P41D$$new;
    function P41K$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P41K$$new = P41K$$new;
    function P41S$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P41S$$new = P41S$$new;
    function P4441$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p4_1.P4441$$new = P4441$$new;
    function P4444$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p4_1.P4444$$new = P4444$$new;
    function P4448$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p4_1.P4448$$new = P4448$$new;
    function P444D$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p4_1.P444D$$new = P444D$$new;
    function P444K$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p4_1.P444K$$new = P444K$$new;
    function P444S$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p4_1.P444S$$new = P444S$$new;
    function P4S1$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P4S1$$new = P4S1$$new;
    function P4S4$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P4S4$$new = P4S4$$new;
    function P4S8$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P4S8$$new = P4S8$$new;
    function P4SD$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P4SD$$new = P4SD$$new;
    function P4SK$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P4SK$$new = P4SK$$new;
    function P4SS$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p4_1.P4SS$$new = P4SS$$new;
})(p4 || (p4 = {}));
//# sourceMappingURL=index.js.map