// Generated by fbsgen from p/ds
import { $change } from '../form';
import mc_ from './mc';
export var ds;
(function (ds) {
    ds.MultiCAS = mc_;
    var ParamId;
    (function (ParamId) {
        function $new(id) {
            return {
                '1': id
            };
        }
        ParamId.$new = $new;
        ParamId.$d = {
            $rfbs: 1, $rfdf: ['1'],
            $fdf: ['1'],
            '1': { _: 1, t: 10, m: 2, a: 0, $: 'id', $n: 'Id' },
            $new: $new, $change: $change
        };
    })(ParamId = ds.ParamId || (ds.ParamId = {}));
    var ParamKey;
    (function (ParamKey) {
        function $new(key, parentKey) {
            return {
                '1': key,
                '2': parentKey
            };
        }
        ParamKey.$new = $new;
        ParamKey.$d = {
            $rfbs: 0,
            $fdikf: ['2'],
            '1': { _: 1, t: 2, m: 2, a: 0, $: 'key', $n: 'Key' },
            '2': { _: 2, t: 2, m: 1, a: 0, $: 'parentKey', $n: 'Parent Key' },
            $new: $new, $change: $change
        };
    })(ParamKey = ds.ParamKey || (ds.ParamKey = {}));
    var ParamUpdate;
    (function (ParamUpdate) {
        function $new(key, mc, id) {
            return {
                '1': key,
                '2': mc,
                '3': id
            };
        }
        ParamUpdate.$new = $new;
        ParamUpdate.$d = {
            $rfbs: 0,
            $fdf: ['3'],
            $fmf: ['2'],
            '1': { _: 1, t: 2, m: 2, a: 0, $: 'key', $n: 'Key' },
            '2': { _: 2, t: 0, m: 2, a: 0, $: 'mc', $n: 'Mc', d_fn: function () { return ds.MultiCAS.$d; } },
            '3': { _: 3, t: 10, m: 1, a: 0, $: 'id', $n: 'Id' },
            $new: $new, $change: $change
        };
    })(ParamUpdate = ds.ParamUpdate || (ds.ParamUpdate = {}));
    var ParamRangeKey;
    (function (ParamRangeKey) {
        function $new(desc, limit, startKey, parentKey) {
            return {
                '1': desc,
                '2': limit,
                '3': startKey,
                '4': parentKey
            };
        }
        ParamRangeKey.$new = $new;
        ParamRangeKey.$d = {
            $rfbs: 1, $rfdf: ['1'],
            $fdf: ['1', '2'],
            $fdikf: ['3', '4'],
            '1': { _: 1, t: 1, m: 2, a: 0, $: 'desc', $n: 'Desc' },
            '2': { _: 2, t: 6, m: 1, a: 0, $: 'limit', $n: 'Limit' },
            '3': { _: 3, t: 2, m: 1, a: 0, $: 'startKey', $n: 'Start Key' },
            '4': { _: 4, t: 2, m: 1, a: 0, $: 'parentKey', $n: 'Parent Key' },
            $new: $new, $change: $change
        };
    })(ParamRangeKey = ds.ParamRangeKey || (ds.ParamRangeKey = {}));
    var ACResult;
    (function (ACResult) {
        function $new(name, value, id) {
            return {
                '1': name,
                '2': value,
                '3': id
            };
        }
        ACResult.$new = $new;
        ACResult.$d = {
            $rfbs: 1, $rfdf: ['1'],
            $fdf: ['1', '3'],
            '1': { _: 1, t: 3, m: 2, a: 0, $: 'name', $n: 'Name' },
            '2': { _: 2, t: 2, m: 2, a: 0, $: 'value', $n: 'Value' },
            '3': { _: 3, t: 10, m: 1, a: 0, $: 'id', $n: 'Id' },
            $new: $new, $change: $change
        };
    })(ACResult = ds.ACResult || (ds.ACResult = {}));
    var P1;
    (function (P1) {
        function $new(value, prk, end, pgstart) {
            return {
                '1': value,
                '2': end,
                '3': pgstart,
                '4': prk
            };
        }
        P1.$new = $new;
        P1.$d = {
            $rfbs: 1, $rfdf: ['1'],
            $fdf: ['1', '2', '3'],
            $fmf: ['4'],
            '1': { _: 1, t: 8, m: 2, a: 0, $: 'value', $n: 'Value' },
            '2': { _: 2, t: 8, m: 1, a: 0, $: 'end', $n: 'End' },
            '3': { _: 3, t: 8, m: 1, a: 0, $: 'pgstart', $n: 'Pgstart' },
            '4': { _: 4, t: 0, m: 2, a: 0, $: 'prk', $n: 'Prk', d_fn: function () { return ParamRangeKey.$d; } },
            $new: $new, $change: $change
        };
    })(P1 = ds.P1 || (ds.P1 = {}));
    var P4;
    (function (P4) {
        function $new(value, prk, end, pgstart) {
            return {
                '1': value,
                '2': end,
                '3': pgstart,
                '4': prk
            };
        }
        P4.$new = $new;
        P4.$d = {
            $rfbs: 1, $rfdf: ['1'],
            $fdf: ['1', '2', '3'],
            $fmf: ['4'],
            '1': { _: 1, t: 6, m: 2, a: 0, $: 'value', $n: 'Value' },
            '2': { _: 2, t: 6, m: 1, a: 0, $: 'end', $n: 'End' },
            '3': { _: 3, t: 6, m: 1, a: 0, $: 'pgstart', $n: 'Pgstart' },
            '4': { _: 4, t: 0, m: 2, a: 0, $: 'prk', $n: 'Prk', d_fn: function () { return ParamRangeKey.$d; } },
            $new: $new, $change: $change
        };
    })(P4 = ds.P4 || (ds.P4 = {}));
    var P8;
    (function (P8) {
        function $new(value, prk, end, pgstart) {
            return {
                '1': value,
                '2': end,
                '3': pgstart,
                '4': prk
            };
        }
        P8.$new = $new;
        P8.$d = {
            $rfbs: 1, $rfdf: ['1'],
            $fdf: ['1', '2', '3'],
            $fmf: ['4'],
            '1': { _: 1, t: 11, m: 2, a: 0, $: 'value', $n: 'Value' },
            '2': { _: 2, t: 11, m: 1, a: 0, $: 'end', $n: 'End' },
            '3': { _: 3, t: 11, m: 1, a: 0, $: 'pgstart', $n: 'Pgstart' },
            '4': { _: 4, t: 0, m: 2, a: 0, $: 'prk', $n: 'Prk', d_fn: function () { return ParamRangeKey.$d; } },
            $new: $new, $change: $change
        };
    })(P8 = ds.P8 || (ds.P8 = {}));
    var PD;
    (function (PD) {
        function $new(value, prk, end, pgstart) {
            return {
                '1': value,
                '2': end,
                '3': pgstart,
                '4': prk
            };
        }
        PD.$new = $new;
        PD.$d = {
            $rfbs: 1, $rfdf: ['1'],
            $fdf: ['1', '2', '3'],
            $fmf: ['4'],
            '1': { _: 1, t: 11, m: 2, a: 0, $: 'value', $n: 'Value' },
            '2': { _: 2, t: 11, m: 1, a: 0, $: 'end', $n: 'End' },
            '3': { _: 3, t: 11, m: 1, a: 0, $: 'pgstart', $n: 'Pgstart' },
            '4': { _: 4, t: 0, m: 2, a: 0, $: 'prk', $n: 'Prk', d_fn: function () { return ParamRangeKey.$d; } },
            $new: $new, $change: $change
        };
    })(PD = ds.PD || (ds.PD = {}));
    var PB;
    (function (PB) {
        function $new(value, prk, end, pgstart) {
            return {
                '1': value,
                '2': end,
                '3': pgstart,
                '4': prk
            };
        }
        PB.$new = $new;
        PB.$d = {
            $rfbs: 0,
            $fmf: ['4'],
            '1': { _: 1, t: 2, m: 2, a: 0, $: 'value', $n: 'Value' },
            '2': { _: 2, t: 2, m: 1, a: 0, $: 'end', $n: 'End' },
            '3': { _: 3, t: 2, m: 1, a: 0, $: 'pgstart', $n: 'Pgstart' },
            '4': { _: 4, t: 0, m: 2, a: 0, $: 'prk', $n: 'Prk', d_fn: function () { return ParamRangeKey.$d; } },
            $new: $new, $change: $change
        };
    })(PB = ds.PB || (ds.PB = {}));
    var PK;
    (function (PK) {
        function $new(value, prk, end, pgstart) {
            return {
                '1': value,
                '2': end,
                '3': pgstart,
                '4': prk
            };
        }
        PK.$new = $new;
        PK.$d = {
            $rfbs: 0,
            $fmf: ['4'],
            '1': { _: 1, t: 2, m: 2, a: 0, $: 'value', $n: 'Value' },
            '2': { _: 2, t: 2, m: 1, a: 0, $: 'end', $n: 'End' },
            '3': { _: 3, t: 2, m: 1, a: 0, $: 'pgstart', $n: 'Pgstart' },
            '4': { _: 4, t: 0, m: 2, a: 0, $: 'prk', $n: 'Prk', d_fn: function () { return ParamRangeKey.$d; } },
            $new: $new, $change: $change
        };
    })(PK = ds.PK || (ds.PK = {}));
    var PS;
    (function (PS) {
        function $new(value, prk, end, pgstart) {
            return {
                '1': value,
                '2': end,
                '3': pgstart,
                '4': prk
            };
        }
        PS.$new = $new;
        PS.$d = {
            $rfbs: 1, $rfdf: ['1'],
            $fdf: ['1', '2', '3'],
            $fmf: ['4'],
            '1': { _: 1, t: 3, m: 2, a: 0, $: 'value', $n: 'Value' },
            '2': { _: 2, t: 3, m: 1, a: 0, $: 'end', $n: 'End' },
            '3': { _: 3, t: 3, m: 1, a: 0, $: 'pgstart', $n: 'Pgstart' },
            '4': { _: 4, t: 0, m: 2, a: 0, $: 'prk', $n: 'Prk', d_fn: function () { return ParamRangeKey.$d; } },
            $new: $new, $change: $change
        };
    })(PS = ds.PS || (ds.PS = {}));
})(ds || (ds = {}));
//# sourceMappingURL=index.js.map