// Generated by fbsgen from p/ds/prk/p1
export var p1;
(function (p1_1) {
    function P181$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P181$$new = P181$$new;
    function P184$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P184$$new = P184$$new;
    function P188$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P188$$new = P188$$new;
    function P18D$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P18D$$new = P18D$$new;
    function P18K$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P18K$$new = P18K$$new;
    function P18S$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P18S$$new = P18S$$new;
    function P111411$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P111411$$new = P111411$$new;
    function P111414$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P111414$$new = P111414$$new;
    function P111418$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P111418$$new = P111418$$new;
    function P11141D$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P11141D$$new = P11141D$$new;
    function P11141K$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P11141K$$new = P11141K$$new;
    function P11141S$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P11141S$$new = P11141S$$new;
    function P1D111$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P1D111$$new = P1D111$$new;
    function P1D114$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P1D114$$new = P1D114$$new;
    function P1D118$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P1D118$$new = P1D118$$new;
    function P1D11D$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P1D11D$$new = P1D11D$$new;
    function P1D11K$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P1D11K$$new = P1D11K$$new;
    function P1D11S$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P1D11S$$new = P1D11S$$new;
    function P141$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P141$$new = P141$$new;
    function P144$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P144$$new = P144$$new;
    function P148$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P148$$new = P148$$new;
    function P14D$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P14D$$new = P14D$$new;
    function P14K$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P14K$$new = P14K$$new;
    function P14S$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P14S$$new = P14S$$new;
    function P1S1$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P1S1$$new = P1S1$$new;
    function P1S4$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P1S4$$new = P1S4$$new;
    function P1S8$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P1S8$$new = P1S8$$new;
    function P1SD$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P1SD$$new = P1SD$$new;
    function P1SK$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P1SK$$new = P1SK$$new;
    function P1SS$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P1SS$$new = P1SS$$new;
    function P1K1$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P1K1$$new = P1K1$$new;
    function P1K4$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P1K4$$new = P1K4$$new;
    function P1K8$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P1K8$$new = P1K8$$new;
    function P1KD$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P1KD$$new = P1KD$$new;
    function P1KK$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P1KK$$new = P1KK$$new;
    function P1KS$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P1KS$$new = P1KS$$new;
    function P1D1$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P1D1$$new = P1D1$$new;
    function P1D4$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P1D4$$new = P1D4$$new;
    function P1D8$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P1D8$$new = P1D8$$new;
    function P1DD$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P1DD$$new = P1DD$$new;
    function P1DK$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P1DK$$new = P1DK$$new;
    function P1DS$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P1DS$$new = P1DS$$new;
    function P1D11$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P1D11$$new = P1D11$$new;
    function P1D14$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P1D14$$new = P1D14$$new;
    function P1D18$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P1D18$$new = P1D18$$new;
    function P1D1D$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P1D1D$$new = P1D1D$$new;
    function P1D1K$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P1D1K$$new = P1D1K$$new;
    function P1D1S$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P1D1S$$new = P1D1S$$new;
    function P11111$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P11111$$new = P11111$$new;
    function P11114$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P11114$$new = P11114$$new;
    function P11118$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P11118$$new = P11118$$new;
    function P1111D$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P1111D$$new = P1111D$$new;
    function P1111K$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P1111K$$new = P1111K$$new;
    function P1111S$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P1111S$$new = P1111S$$new;
    function P111$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P111$$new = P111$$new;
    function P114$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P114$$new = P114$$new;
    function P118$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P118$$new = P118$$new;
    function P11D$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P11D$$new = P11D$$new;
    function P11K$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P11K$$new = P11K$$new;
    function P11S$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p1_1.P11S$$new = P11S$$new;
    function P111K1$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P111K1$$new = P111K1$$new;
    function P111K4$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P111K4$$new = P111K4$$new;
    function P111K8$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P111K8$$new = P111K8$$new;
    function P111KD$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P111KD$$new = P111KD$$new;
    function P111KK$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P111KK$$new = P111KK$$new;
    function P111KS$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P111KS$$new = P111KS$$new;
    function P1141$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P1141$$new = P1141$$new;
    function P1144$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P1144$$new = P1144$$new;
    function P1148$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P1148$$new = P1148$$new;
    function P114D$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P114D$$new = P114D$$new;
    function P114K$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P114K$$new = P114K$$new;
    function P114S$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P114S$$new = P114S$$new;
    function P11K1$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P11K1$$new = P11K1$$new;
    function P11K4$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P11K4$$new = P11K4$$new;
    function P11K8$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P11K8$$new = P11K8$$new;
    function P11KD$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P11KD$$new = P11KD$$new;
    function P11KK$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P11KK$$new = P11KK$$new;
    function P11KS$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P11KS$$new = P11KS$$new;
    function P1DK1$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P1DK1$$new = P1DK1$$new;
    function P1DK4$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P1DK4$$new = P1DK4$$new;
    function P1DK8$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P1DK8$$new = P1DK8$$new;
    function P1DKD$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P1DKD$$new = P1DKD$$new;
    function P1DKK$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P1DKK$$new = P1DKK$$new;
    function P1DKS$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P1DKS$$new = P1DKS$$new;
    function P14441$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P14441$$new = P14441$$new;
    function P14444$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P14444$$new = P14444$$new;
    function P14448$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P14448$$new = P14448$$new;
    function P1444D$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P1444D$$new = P1444D$$new;
    function P1444K$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P1444K$$new = P1444K$$new;
    function P1444S$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P1444S$$new = P1444S$$new;
    function P111111$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P111111$$new = P111111$$new;
    function P111114$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P111114$$new = P111114$$new;
    function P111118$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P111118$$new = P111118$$new;
    function P11111D$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P11111D$$new = P11111D$$new;
    function P11111K$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P11111K$$new = P11111K$$new;
    function P11111S$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P11111S$$new = P11111S$$new;
    function P1D1111$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P1D1111$$new = P1D1111$$new;
    function P1D1114$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P1D1114$$new = P1D1114$$new;
    function P1D1118$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P1D1118$$new = P1D1118$$new;
    function P1D111D$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P1D111D$$new = P1D111D$$new;
    function P1D111K$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P1D111K$$new = P1D111K$$new;
    function P1D111S$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P1D111S$$new = P1D111S$$new;
    function P111141$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P111141$$new = P111141$$new;
    function P111144$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P111144$$new = P111144$$new;
    function P111148$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P111148$$new = P111148$$new;
    function P11114D$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P11114D$$new = P11114D$$new;
    function P11114K$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P11114K$$new = P11114K$$new;
    function P11114S$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P11114S$$new = P11114S$$new;
    function P11$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    p1_1.P11$$new = P11$$new;
    function P14$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    p1_1.P14$$new = P14$$new;
    function P18$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    p1_1.P18$$new = P18$$new;
    function P1D$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    p1_1.P1D$$new = P1D$$new;
    function P1K$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    p1_1.P1K$$new = P1K$$new;
    function P1S$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    p1_1.P1S$$new = P1S$$new;
    function P111K11$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P111K11$$new = P111K11$$new;
    function P111K14$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P111K14$$new = P111K14$$new;
    function P111K18$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P111K18$$new = P111K18$$new;
    function P111K1D$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P111K1D$$new = P111K1D$$new;
    function P111K1K$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P111K1K$$new = P111K1K$$new;
    function P111K1S$$new(p0, p1, p2, p3, p4, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        };
    }
    p1_1.P111K1S$$new = P111K1S$$new;
    function P1441$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P1441$$new = P1441$$new;
    function P1444$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P1444$$new = P1444$$new;
    function P1448$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P1448$$new = P1448$$new;
    function P144D$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P144D$$new = P144D$$new;
    function P144K$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P144K$$new = P144K$$new;
    function P144S$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P144S$$new = P144S$$new;
    function P1111$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P1111$$new = P1111$$new;
    function P1114$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P1114$$new = P1114$$new;
    function P1118$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P1118$$new = P1118$$new;
    function P111D$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P111D$$new = P111D$$new;
    function P111K$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P111K$$new = P111K$$new;
    function P111S$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P111S$$new = P111S$$new;
    function P11S1$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P11S1$$new = P11S1$$new;
    function P11S4$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P11S4$$new = P11S4$$new;
    function P11S8$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P11S8$$new = P11S8$$new;
    function P11SD$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P11SD$$new = P11SD$$new;
    function P11SK$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P11SK$$new = P11SK$$new;
    function P11SS$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    p1_1.P11SS$$new = P11SS$$new;
    function P1DK11$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P1DK11$$new = P1DK11$$new;
    function P1DK14$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P1DK14$$new = P1DK14$$new;
    function P1DK18$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P1DK18$$new = P1DK18$$new;
    function P1DK1D$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P1DK1D$$new = P1DK1D$$new;
    function P1DK1K$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P1DK1K$$new = P1DK1K$$new;
    function P1DK1S$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P1DK1S$$new = P1DK1S$$new;
    function P11141$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P11141$$new = P11141$$new;
    function P11144$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P11144$$new = P11144$$new;
    function P11148$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P11148$$new = P11148$$new;
    function P1114D$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P1114D$$new = P1114D$$new;
    function P1114K$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P1114K$$new = P1114K$$new;
    function P1114S$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    p1_1.P1114S$$new = P1114S$$new;
})(p1 || (p1 = {}));
//# sourceMappingURL=index.js.map