// Generated by fbsgen from p/ds/prk/p8
export var p8;
(function (p8) {
    function P8D1$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P8D1$$new = P8D1$$new;
    function P8D4$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P8D4$$new = P8D4$$new;
    function P8D8$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P8D8$$new = P8D8$$new;
    function P8DD$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P8DD$$new = P8DD$$new;
    function P8DK$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P8DK$$new = P8DK$$new;
    function P8DS$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P8DS$$new = P8DS$$new;
    function P81$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    p8.P81$$new = P81$$new;
    function P84$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    p8.P84$$new = P84$$new;
    function P88$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    p8.P88$$new = P88$$new;
    function P8D$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    p8.P8D$$new = P8D$$new;
    function P8K$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    p8.P8K$$new = P8K$$new;
    function P8S$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    p8.P8S$$new = P8S$$new;
    function P881$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P881$$new = P881$$new;
    function P884$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P884$$new = P884$$new;
    function P888$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P888$$new = P888$$new;
    function P88D$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P88D$$new = P88D$$new;
    function P88K$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P88K$$new = P88K$$new;
    function P88S$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P88S$$new = P88S$$new;
    function P8K1$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P8K1$$new = P8K1$$new;
    function P8K4$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P8K4$$new = P8K4$$new;
    function P8K8$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P8K8$$new = P8K8$$new;
    function P8KD$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P8KD$$new = P8KD$$new;
    function P8KK$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P8KK$$new = P8KK$$new;
    function P8KS$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P8KS$$new = P8KS$$new;
    function P841$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P841$$new = P841$$new;
    function P844$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P844$$new = P844$$new;
    function P848$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P848$$new = P848$$new;
    function P84D$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P84D$$new = P84D$$new;
    function P84K$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P84K$$new = P84K$$new;
    function P84S$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P84S$$new = P84S$$new;
    function P811$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P811$$new = P811$$new;
    function P814$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P814$$new = P814$$new;
    function P818$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P818$$new = P818$$new;
    function P81D$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P81D$$new = P81D$$new;
    function P81K$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P81K$$new = P81K$$new;
    function P81S$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P81S$$new = P81S$$new;
    function P8S1$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P8S1$$new = P8S1$$new;
    function P8S4$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P8S4$$new = P8S4$$new;
    function P8S8$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P8S8$$new = P8S8$$new;
    function P8SD$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P8SD$$new = P8SD$$new;
    function P8SK$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P8SK$$new = P8SK$$new;
    function P8SS$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    p8.P8SS$$new = P8SS$$new;
})(p8 || (p8 = {}));
//# sourceMappingURL=index.js.map