// Generated by fbsgen from p/ds/prk/ps
export var ps;
(function (ps) {
    function PS111$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    ps.PS111$$new = PS111$$new;
    function PS114$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    ps.PS114$$new = PS114$$new;
    function PS118$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    ps.PS118$$new = PS118$$new;
    function PS11D$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    ps.PS11D$$new = PS11D$$new;
    function PS11K$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    ps.PS11K$$new = PS11K$$new;
    function PS11S$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    ps.PS11S$$new = PS11S$$new;
    function PS41$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PS41$$new = PS41$$new;
    function PS44$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PS44$$new = PS44$$new;
    function PS48$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PS48$$new = PS48$$new;
    function PS4D$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PS4D$$new = PS4D$$new;
    function PS4K$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PS4K$$new = PS4K$$new;
    function PS4S$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PS4S$$new = PS4S$$new;
    function PSK1$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PSK1$$new = PSK1$$new;
    function PSK4$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PSK4$$new = PSK4$$new;
    function PSK8$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PSK8$$new = PSK8$$new;
    function PSKD$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PSKD$$new = PSKD$$new;
    function PSKK$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PSKK$$new = PSKK$$new;
    function PSKS$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PSKS$$new = PSKS$$new;
    function PS11$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PS11$$new = PS11$$new;
    function PS14$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PS14$$new = PS14$$new;
    function PS18$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PS18$$new = PS18$$new;
    function PS1D$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PS1D$$new = PS1D$$new;
    function PS1K$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PS1K$$new = PS1K$$new;
    function PS1S$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PS1S$$new = PS1S$$new;
    function PSS1$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PSS1$$new = PSS1$$new;
    function PSS4$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PSS4$$new = PSS4$$new;
    function PSS8$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PSS8$$new = PSS8$$new;
    function PSSD$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PSSD$$new = PSSD$$new;
    function PSSK$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PSSK$$new = PSSK$$new;
    function PSSS$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PSSS$$new = PSSS$$new;
    function PSD1$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PSD1$$new = PSD1$$new;
    function PSD4$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PSD4$$new = PSD4$$new;
    function PSD8$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PSD8$$new = PSD8$$new;
    function PSDD$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PSDD$$new = PSDD$$new;
    function PSDK$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PSDK$$new = PSDK$$new;
    function PSDS$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PSDS$$new = PSDS$$new;
    function PS81$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PS81$$new = PS81$$new;
    function PS84$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PS84$$new = PS84$$new;
    function PS88$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PS88$$new = PS88$$new;
    function PS8D$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PS8D$$new = PS8D$$new;
    function PS8K$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PS8K$$new = PS8K$$new;
    function PS8S$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    ps.PS8S$$new = PS8S$$new;
    function PS1$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    ps.PS1$$new = PS1$$new;
    function PS4$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    ps.PS4$$new = PS4$$new;
    function PS8$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    ps.PS8$$new = PS8$$new;
    function PSD$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    ps.PSD$$new = PSD$$new;
    function PSK$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    ps.PSK$$new = PSK$$new;
    function PSS$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    ps.PSS$$new = PSS$$new;
})(ps || (ps = {}));
//# sourceMappingURL=index.js.map