// Generated by fbsgen from p/ds/prk/ps

import { ds } from '../../'

export namespace ps {
    /**
     * ```
     * 
     * message PS111 {
     *   required string p0 = 1;
     *   required int8 p1 = 2;
     *   required int8 p2 = 3;
     *   required ds.P1 l = 4;
     * }
     * ```
     */
    export interface PS111 {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** l = 4, required */
        ['4']: ds.P1
    }
    export function PS111$$new(p0: string, p1: number, p2: number, l: ds.P1): PS111 {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        }
    }

    /**
     * ```
     * 
     * message PS114 {
     *   required string p0 = 1;
     *   required int8 p1 = 2;
     *   required int8 p2 = 3;
     *   required ds.P4 l = 4;
     * }
     * ```
     */
    export interface PS114 {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** l = 4, required */
        ['4']: ds.P4
    }
    export function PS114$$new(p0: string, p1: number, p2: number, l: ds.P4): PS114 {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        }
    }

    /**
     * ```
     * 
     * message PS118 {
     *   required string p0 = 1;
     *   required int8 p1 = 2;
     *   required int8 p2 = 3;
     *   required ds.P8 l = 4;
     * }
     * ```
     */
    export interface PS118 {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** l = 4, required */
        ['4']: ds.P8
    }
    export function PS118$$new(p0: string, p1: number, p2: number, l: ds.P8): PS118 {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        }
    }

    /**
     * ```
     * 
     * message PS11D {
     *   required string p0 = 1;
     *   required int8 p1 = 2;
     *   required int8 p2 = 3;
     *   required ds.PD l = 4;
     * }
     * ```
     */
    export interface PS11D {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** l = 4, required */
        ['4']: ds.PD
    }
    export function PS11D$$new(p0: string, p1: number, p2: number, l: ds.PD): PS11D {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        }
    }

    /**
     * ```
     * 
     * message PS11K {
     *   required string p0 = 1;
     *   required int8 p1 = 2;
     *   required int8 p2 = 3;
     *   required ds.PK l = 4;
     * }
     * ```
     */
    export interface PS11K {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** l = 4, required */
        ['4']: ds.PK
    }
    export function PS11K$$new(p0: string, p1: number, p2: number, l: ds.PK): PS11K {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        }
    }

    /**
     * ```
     * 
     * message PS11S {
     *   required string p0 = 1;
     *   required int8 p1 = 2;
     *   required int8 p2 = 3;
     *   required ds.PS l = 4;
     * }
     * ```
     */
    export interface PS11S {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** l = 4, required */
        ['4']: ds.PS
    }
    export function PS11S$$new(p0: string, p1: number, p2: number, l: ds.PS): PS11S {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        }
    }


    /**
     * ```
     * 
     * message PS41 {
     *   required string p0 = 1;
     *   required uint32 p1 = 2;
     *   required ds.P1 l = 3;
     * }
     * ```
     */
    export interface PS41 {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P1
    }
    export function PS41$$new(p0: string, p1: number, l: ds.P1): PS41 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PS44 {
     *   required string p0 = 1;
     *   required uint32 p1 = 2;
     *   required ds.P4 l = 3;
     * }
     * ```
     */
    export interface PS44 {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P4
    }
    export function PS44$$new(p0: string, p1: number, l: ds.P4): PS44 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PS48 {
     *   required string p0 = 1;
     *   required uint32 p1 = 2;
     *   required ds.P8 l = 3;
     * }
     * ```
     */
    export interface PS48 {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P8
    }
    export function PS48$$new(p0: string, p1: number, l: ds.P8): PS48 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PS4D {
     *   required string p0 = 1;
     *   required uint32 p1 = 2;
     *   required ds.PD l = 3;
     * }
     * ```
     */
    export interface PS4D {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PD
    }
    export function PS4D$$new(p0: string, p1: number, l: ds.PD): PS4D {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PS4K {
     *   required string p0 = 1;
     *   required uint32 p1 = 2;
     *   required ds.PK l = 3;
     * }
     * ```
     */
    export interface PS4K {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PK
    }
    export function PS4K$$new(p0: string, p1: number, l: ds.PK): PS4K {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PS4S {
     *   required string p0 = 1;
     *   required uint32 p1 = 2;
     *   required ds.PS l = 3;
     * }
     * ```
     */
    export interface PS4S {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PS
    }
    export function PS4S$$new(p0: string, p1: number, l: ds.PS): PS4S {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }


    /**
     * ```
     * 
     * message PSK1 {
     *   required string p0 = 1;
     *   required bytes p1 = 2;
     *   required ds.P1 l = 3;
     * }
     * ```
     */
    export interface PSK1 {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.P1
    }
    export function PSK1$$new(p0: string, p1: string, l: ds.P1): PSK1 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PSK4 {
     *   required string p0 = 1;
     *   required bytes p1 = 2;
     *   required ds.P4 l = 3;
     * }
     * ```
     */
    export interface PSK4 {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.P4
    }
    export function PSK4$$new(p0: string, p1: string, l: ds.P4): PSK4 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PSK8 {
     *   required string p0 = 1;
     *   required bytes p1 = 2;
     *   required ds.P8 l = 3;
     * }
     * ```
     */
    export interface PSK8 {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.P8
    }
    export function PSK8$$new(p0: string, p1: string, l: ds.P8): PSK8 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PSKD {
     *   required string p0 = 1;
     *   required bytes p1 = 2;
     *   required ds.PD l = 3;
     * }
     * ```
     */
    export interface PSKD {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.PD
    }
    export function PSKD$$new(p0: string, p1: string, l: ds.PD): PSKD {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PSKK {
     *   required string p0 = 1;
     *   required bytes p1 = 2;
     *   required ds.PK l = 3;
     * }
     * ```
     */
    export interface PSKK {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.PK
    }
    export function PSKK$$new(p0: string, p1: string, l: ds.PK): PSKK {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PSKS {
     *   required string p0 = 1;
     *   required bytes p1 = 2;
     *   required ds.PS l = 3;
     * }
     * ```
     */
    export interface PSKS {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.PS
    }
    export function PSKS$$new(p0: string, p1: string, l: ds.PS): PSKS {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }


    /**
     * ```
     * 
     * message PS11 {
     *   required string p0 = 1;
     *   required int8 p1 = 2;
     *   required ds.P1 l = 3;
     * }
     * ```
     */
    export interface PS11 {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P1
    }
    export function PS11$$new(p0: string, p1: number, l: ds.P1): PS11 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PS14 {
     *   required string p0 = 1;
     *   required int8 p1 = 2;
     *   required ds.P4 l = 3;
     * }
     * ```
     */
    export interface PS14 {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P4
    }
    export function PS14$$new(p0: string, p1: number, l: ds.P4): PS14 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PS18 {
     *   required string p0 = 1;
     *   required int8 p1 = 2;
     *   required ds.P8 l = 3;
     * }
     * ```
     */
    export interface PS18 {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P8
    }
    export function PS18$$new(p0: string, p1: number, l: ds.P8): PS18 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PS1D {
     *   required string p0 = 1;
     *   required int8 p1 = 2;
     *   required ds.PD l = 3;
     * }
     * ```
     */
    export interface PS1D {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PD
    }
    export function PS1D$$new(p0: string, p1: number, l: ds.PD): PS1D {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PS1K {
     *   required string p0 = 1;
     *   required int8 p1 = 2;
     *   required ds.PK l = 3;
     * }
     * ```
     */
    export interface PS1K {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PK
    }
    export function PS1K$$new(p0: string, p1: number, l: ds.PK): PS1K {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PS1S {
     *   required string p0 = 1;
     *   required int8 p1 = 2;
     *   required ds.PS l = 3;
     * }
     * ```
     */
    export interface PS1S {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PS
    }
    export function PS1S$$new(p0: string, p1: number, l: ds.PS): PS1S {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }


    /**
     * ```
     * 
     * message PSS1 {
     *   required string p0 = 1;
     *   required string p1 = 2;
     *   required ds.P1 l = 3;
     * }
     * ```
     */
    export interface PSS1 {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.P1
    }
    export function PSS1$$new(p0: string, p1: string, l: ds.P1): PSS1 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PSS4 {
     *   required string p0 = 1;
     *   required string p1 = 2;
     *   required ds.P4 l = 3;
     * }
     * ```
     */
    export interface PSS4 {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.P4
    }
    export function PSS4$$new(p0: string, p1: string, l: ds.P4): PSS4 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PSS8 {
     *   required string p0 = 1;
     *   required string p1 = 2;
     *   required ds.P8 l = 3;
     * }
     * ```
     */
    export interface PSS8 {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.P8
    }
    export function PSS8$$new(p0: string, p1: string, l: ds.P8): PSS8 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PSSD {
     *   required string p0 = 1;
     *   required string p1 = 2;
     *   required ds.PD l = 3;
     * }
     * ```
     */
    export interface PSSD {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.PD
    }
    export function PSSD$$new(p0: string, p1: string, l: ds.PD): PSSD {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PSSK {
     *   required string p0 = 1;
     *   required string p1 = 2;
     *   required ds.PK l = 3;
     * }
     * ```
     */
    export interface PSSK {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.PK
    }
    export function PSSK$$new(p0: string, p1: string, l: ds.PK): PSSK {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PSSS {
     *   required string p0 = 1;
     *   required string p1 = 2;
     *   required ds.PS l = 3;
     * }
     * ```
     */
    export interface PSSS {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.PS
    }
    export function PSSS$$new(p0: string, p1: string, l: ds.PS): PSSS {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }


    /**
     * ```
     * 
     * message PSD1 {
     *   required string p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.P1 l = 3;
     * }
     * ```
     */
    export interface PSD1 {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P1
    }
    export function PSD1$$new(p0: string, p1: number, l: ds.P1): PSD1 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PSD4 {
     *   required string p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.P4 l = 3;
     * }
     * ```
     */
    export interface PSD4 {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P4
    }
    export function PSD4$$new(p0: string, p1: number, l: ds.P4): PSD4 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PSD8 {
     *   required string p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.P8 l = 3;
     * }
     * ```
     */
    export interface PSD8 {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P8
    }
    export function PSD8$$new(p0: string, p1: number, l: ds.P8): PSD8 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PSDD {
     *   required string p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.PD l = 3;
     * }
     * ```
     */
    export interface PSDD {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PD
    }
    export function PSDD$$new(p0: string, p1: number, l: ds.PD): PSDD {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PSDK {
     *   required string p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.PK l = 3;
     * }
     * ```
     */
    export interface PSDK {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PK
    }
    export function PSDK$$new(p0: string, p1: number, l: ds.PK): PSDK {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PSDS {
     *   required string p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.PS l = 3;
     * }
     * ```
     */
    export interface PSDS {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PS
    }
    export function PSDS$$new(p0: string, p1: number, l: ds.PS): PSDS {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }


    /**
     * ```
     * 
     * message PS81 {
     *   required string p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.P1 l = 3;
     * }
     * ```
     */
    export interface PS81 {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P1
    }
    export function PS81$$new(p0: string, p1: number, l: ds.P1): PS81 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PS84 {
     *   required string p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.P4 l = 3;
     * }
     * ```
     */
    export interface PS84 {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P4
    }
    export function PS84$$new(p0: string, p1: number, l: ds.P4): PS84 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PS88 {
     *   required string p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.P8 l = 3;
     * }
     * ```
     */
    export interface PS88 {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P8
    }
    export function PS88$$new(p0: string, p1: number, l: ds.P8): PS88 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PS8D {
     *   required string p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.PD l = 3;
     * }
     * ```
     */
    export interface PS8D {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PD
    }
    export function PS8D$$new(p0: string, p1: number, l: ds.PD): PS8D {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PS8K {
     *   required string p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.PK l = 3;
     * }
     * ```
     */
    export interface PS8K {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PK
    }
    export function PS8K$$new(p0: string, p1: number, l: ds.PK): PS8K {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message PS8S {
     *   required string p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.PS l = 3;
     * }
     * ```
     */
    export interface PS8S {
        /** p0 = 1, required */
        ['1']: string
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PS
    }
    export function PS8S$$new(p0: string, p1: number, l: ds.PS): PS8S {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }


    /**
     * ```
     * 
     * message PS1 {
     *   required string p0 = 1;
     *   required ds.P1 l = 2;
     * }
     * ```
     */
    export interface PS1 {
        /** p0 = 1, required */
        ['1']: string
        /** l = 2, required */
        ['2']: ds.P1
    }
    export function PS1$$new(p0: string, l: ds.P1): PS1 {
        return {
            '1': p0,
            '2': l
        }
    }

    /**
     * ```
     * 
     * message PS4 {
     *   required string p0 = 1;
     *   required ds.P4 l = 2;
     * }
     * ```
     */
    export interface PS4 {
        /** p0 = 1, required */
        ['1']: string
        /** l = 2, required */
        ['2']: ds.P4
    }
    export function PS4$$new(p0: string, l: ds.P4): PS4 {
        return {
            '1': p0,
            '2': l
        }
    }

    /**
     * ```
     * 
     * message PS8 {
     *   required string p0 = 1;
     *   required ds.P8 l = 2;
     * }
     * ```
     */
    export interface PS8 {
        /** p0 = 1, required */
        ['1']: string
        /** l = 2, required */
        ['2']: ds.P8
    }
    export function PS8$$new(p0: string, l: ds.P8): PS8 {
        return {
            '1': p0,
            '2': l
        }
    }

    /**
     * ```
     * 
     * message PSD {
     *   required string p0 = 1;
     *   required ds.PD l = 2;
     * }
     * ```
     */
    export interface PSD {
        /** p0 = 1, required */
        ['1']: string
        /** l = 2, required */
        ['2']: ds.PD
    }
    export function PSD$$new(p0: string, l: ds.PD): PSD {
        return {
            '1': p0,
            '2': l
        }
    }

    /**
     * ```
     * 
     * message PSK {
     *   required string p0 = 1;
     *   required ds.PK l = 2;
     * }
     * ```
     */
    export interface PSK {
        /** p0 = 1, required */
        ['1']: string
        /** l = 2, required */
        ['2']: ds.PK
    }
    export function PSK$$new(p0: string, l: ds.PK): PSK {
        return {
            '1': p0,
            '2': l
        }
    }

    /**
     * ```
     * 
     * message PSS {
     *   required string p0 = 1;
     *   required ds.PS l = 2;
     * }
     * ```
     */
    export interface PSS {
        /** p0 = 1, required */
        ['1']: string
        /** l = 2, required */
        ['2']: ds.PS
    }
    export function PSS$$new(p0: string, l: ds.PS): PSS {
        return {
            '1': p0,
            '2': l
        }
    }



}

