// Generated by fbsgen from p/ds/prk/p4

import { ds } from '../../'

export namespace p4 {
    /**
     * ```
     * 
     * message P4D1 {
     *   required uint32 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.P1 l = 3;
     * }
     * ```
     */
    export interface P4D1 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P1
    }
    export function P4D1$$new(p0: number, p1: number, l: ds.P1): P4D1 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P4D4 {
     *   required uint32 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.P4 l = 3;
     * }
     * ```
     */
    export interface P4D4 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P4
    }
    export function P4D4$$new(p0: number, p1: number, l: ds.P4): P4D4 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P4D8 {
     *   required uint32 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.P8 l = 3;
     * }
     * ```
     */
    export interface P4D8 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P8
    }
    export function P4D8$$new(p0: number, p1: number, l: ds.P8): P4D8 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P4DD {
     *   required uint32 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.PD l = 3;
     * }
     * ```
     */
    export interface P4DD {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PD
    }
    export function P4DD$$new(p0: number, p1: number, l: ds.PD): P4DD {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P4DK {
     *   required uint32 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.PK l = 3;
     * }
     * ```
     */
    export interface P4DK {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PK
    }
    export function P4DK$$new(p0: number, p1: number, l: ds.PK): P4DK {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P4DS {
     *   required uint32 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.PS l = 3;
     * }
     * ```
     */
    export interface P4DS {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PS
    }
    export function P4DS$$new(p0: number, p1: number, l: ds.PS): P4DS {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }


    /**
     * ```
     * 
     * message P44441 {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required uint32 p2 = 3;
     *   required uint32 p3 = 4;
     *   required ds.P1 l = 5;
     * }
     * ```
     */
    export interface P44441 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** p3 = 4, required */
        ['4']: number
        /** l = 5, required */
        ['5']: ds.P1
    }
    export function P44441$$new(p0: number, p1: number, p2: number, p3: number, l: ds.P1): P44441 {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        }
    }

    /**
     * ```
     * 
     * message P44444 {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required uint32 p2 = 3;
     *   required uint32 p3 = 4;
     *   required ds.P4 l = 5;
     * }
     * ```
     */
    export interface P44444 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** p3 = 4, required */
        ['4']: number
        /** l = 5, required */
        ['5']: ds.P4
    }
    export function P44444$$new(p0: number, p1: number, p2: number, p3: number, l: ds.P4): P44444 {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        }
    }

    /**
     * ```
     * 
     * message P44448 {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required uint32 p2 = 3;
     *   required uint32 p3 = 4;
     *   required ds.P8 l = 5;
     * }
     * ```
     */
    export interface P44448 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** p3 = 4, required */
        ['4']: number
        /** l = 5, required */
        ['5']: ds.P8
    }
    export function P44448$$new(p0: number, p1: number, p2: number, p3: number, l: ds.P8): P44448 {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        }
    }

    /**
     * ```
     * 
     * message P4444D {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required uint32 p2 = 3;
     *   required uint32 p3 = 4;
     *   required ds.PD l = 5;
     * }
     * ```
     */
    export interface P4444D {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** p3 = 4, required */
        ['4']: number
        /** l = 5, required */
        ['5']: ds.PD
    }
    export function P4444D$$new(p0: number, p1: number, p2: number, p3: number, l: ds.PD): P4444D {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        }
    }

    /**
     * ```
     * 
     * message P4444K {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required uint32 p2 = 3;
     *   required uint32 p3 = 4;
     *   required ds.PK l = 5;
     * }
     * ```
     */
    export interface P4444K {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** p3 = 4, required */
        ['4']: number
        /** l = 5, required */
        ['5']: ds.PK
    }
    export function P4444K$$new(p0: number, p1: number, p2: number, p3: number, l: ds.PK): P4444K {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        }
    }

    /**
     * ```
     * 
     * message P4444S {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required uint32 p2 = 3;
     *   required uint32 p3 = 4;
     *   required ds.PS l = 5;
     * }
     * ```
     */
    export interface P4444S {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** p3 = 4, required */
        ['4']: number
        /** l = 5, required */
        ['5']: ds.PS
    }
    export function P4444S$$new(p0: number, p1: number, p2: number, p3: number, l: ds.PS): P4444S {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        }
    }


    /**
     * ```
     * 
     * message P481 {
     *   required uint32 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.P1 l = 3;
     * }
     * ```
     */
    export interface P481 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P1
    }
    export function P481$$new(p0: number, p1: number, l: ds.P1): P481 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P484 {
     *   required uint32 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.P4 l = 3;
     * }
     * ```
     */
    export interface P484 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P4
    }
    export function P484$$new(p0: number, p1: number, l: ds.P4): P484 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P488 {
     *   required uint32 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.P8 l = 3;
     * }
     * ```
     */
    export interface P488 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P8
    }
    export function P488$$new(p0: number, p1: number, l: ds.P8): P488 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P48D {
     *   required uint32 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.PD l = 3;
     * }
     * ```
     */
    export interface P48D {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PD
    }
    export function P48D$$new(p0: number, p1: number, l: ds.PD): P48D {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P48K {
     *   required uint32 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.PK l = 3;
     * }
     * ```
     */
    export interface P48K {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PK
    }
    export function P48K$$new(p0: number, p1: number, l: ds.PK): P48K {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P48S {
     *   required uint32 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.PS l = 3;
     * }
     * ```
     */
    export interface P48S {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PS
    }
    export function P48S$$new(p0: number, p1: number, l: ds.PS): P48S {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }


    /**
     * ```
     * 
     * message P444441 {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required uint32 p2 = 3;
     *   required uint32 p3 = 4;
     *   required uint32 p4 = 5;
     *   required ds.P1 l = 6;
     * }
     * ```
     */
    export interface P444441 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** p3 = 4, required */
        ['4']: number
        /** p4 = 5, required */
        ['5']: number
        /** l = 6, required */
        ['6']: ds.P1
    }
    export function P444441$$new(p0: number, p1: number, p2: number, p3: number, p4: number, l: ds.P1): P444441 {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        }
    }

    /**
     * ```
     * 
     * message P444444 {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required uint32 p2 = 3;
     *   required uint32 p3 = 4;
     *   required uint32 p4 = 5;
     *   required ds.P4 l = 6;
     * }
     * ```
     */
    export interface P444444 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** p3 = 4, required */
        ['4']: number
        /** p4 = 5, required */
        ['5']: number
        /** l = 6, required */
        ['6']: ds.P4
    }
    export function P444444$$new(p0: number, p1: number, p2: number, p3: number, p4: number, l: ds.P4): P444444 {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        }
    }

    /**
     * ```
     * 
     * message P444448 {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required uint32 p2 = 3;
     *   required uint32 p3 = 4;
     *   required uint32 p4 = 5;
     *   required ds.P8 l = 6;
     * }
     * ```
     */
    export interface P444448 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** p3 = 4, required */
        ['4']: number
        /** p4 = 5, required */
        ['5']: number
        /** l = 6, required */
        ['6']: ds.P8
    }
    export function P444448$$new(p0: number, p1: number, p2: number, p3: number, p4: number, l: ds.P8): P444448 {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        }
    }

    /**
     * ```
     * 
     * message P44444D {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required uint32 p2 = 3;
     *   required uint32 p3 = 4;
     *   required uint32 p4 = 5;
     *   required ds.PD l = 6;
     * }
     * ```
     */
    export interface P44444D {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** p3 = 4, required */
        ['4']: number
        /** p4 = 5, required */
        ['5']: number
        /** l = 6, required */
        ['6']: ds.PD
    }
    export function P44444D$$new(p0: number, p1: number, p2: number, p3: number, p4: number, l: ds.PD): P44444D {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        }
    }

    /**
     * ```
     * 
     * message P44444K {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required uint32 p2 = 3;
     *   required uint32 p3 = 4;
     *   required uint32 p4 = 5;
     *   required ds.PK l = 6;
     * }
     * ```
     */
    export interface P44444K {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** p3 = 4, required */
        ['4']: number
        /** p4 = 5, required */
        ['5']: number
        /** l = 6, required */
        ['6']: ds.PK
    }
    export function P44444K$$new(p0: number, p1: number, p2: number, p3: number, p4: number, l: ds.PK): P44444K {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        }
    }

    /**
     * ```
     * 
     * message P44444S {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required uint32 p2 = 3;
     *   required uint32 p3 = 4;
     *   required uint32 p4 = 5;
     *   required ds.PS l = 6;
     * }
     * ```
     */
    export interface P44444S {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** p3 = 4, required */
        ['4']: number
        /** p4 = 5, required */
        ['5']: number
        /** l = 6, required */
        ['6']: ds.PS
    }
    export function P44444S$$new(p0: number, p1: number, p2: number, p3: number, p4: number, l: ds.PS): P44444S {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': p4,
            '6': l
        }
    }


    /**
     * ```
     * 
     * message P441 {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required ds.P1 l = 3;
     * }
     * ```
     */
    export interface P441 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P1
    }
    export function P441$$new(p0: number, p1: number, l: ds.P1): P441 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P444 {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required ds.P4 l = 3;
     * }
     * ```
     */
    export interface P444 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P4
    }
    export function P444$$new(p0: number, p1: number, l: ds.P4): P444 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P448 {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required ds.P8 l = 3;
     * }
     * ```
     */
    export interface P448 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P8
    }
    export function P448$$new(p0: number, p1: number, l: ds.P8): P448 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P44D {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required ds.PD l = 3;
     * }
     * ```
     */
    export interface P44D {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PD
    }
    export function P44D$$new(p0: number, p1: number, l: ds.PD): P44D {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P44K {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required ds.PK l = 3;
     * }
     * ```
     */
    export interface P44K {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PK
    }
    export function P44K$$new(p0: number, p1: number, l: ds.PK): P44K {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P44S {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required ds.PS l = 3;
     * }
     * ```
     */
    export interface P44S {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PS
    }
    export function P44S$$new(p0: number, p1: number, l: ds.PS): P44S {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }


    /**
     * ```
     * 
     * message P4K1 {
     *   required uint32 p0 = 1;
     *   required bytes p1 = 2;
     *   required ds.P1 l = 3;
     * }
     * ```
     */
    export interface P4K1 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.P1
    }
    export function P4K1$$new(p0: number, p1: string, l: ds.P1): P4K1 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P4K4 {
     *   required uint32 p0 = 1;
     *   required bytes p1 = 2;
     *   required ds.P4 l = 3;
     * }
     * ```
     */
    export interface P4K4 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.P4
    }
    export function P4K4$$new(p0: number, p1: string, l: ds.P4): P4K4 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P4K8 {
     *   required uint32 p0 = 1;
     *   required bytes p1 = 2;
     *   required ds.P8 l = 3;
     * }
     * ```
     */
    export interface P4K8 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.P8
    }
    export function P4K8$$new(p0: number, p1: string, l: ds.P8): P4K8 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P4KD {
     *   required uint32 p0 = 1;
     *   required bytes p1 = 2;
     *   required ds.PD l = 3;
     * }
     * ```
     */
    export interface P4KD {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.PD
    }
    export function P4KD$$new(p0: number, p1: string, l: ds.PD): P4KD {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P4KK {
     *   required uint32 p0 = 1;
     *   required bytes p1 = 2;
     *   required ds.PK l = 3;
     * }
     * ```
     */
    export interface P4KK {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.PK
    }
    export function P4KK$$new(p0: number, p1: string, l: ds.PK): P4KK {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P4KS {
     *   required uint32 p0 = 1;
     *   required bytes p1 = 2;
     *   required ds.PS l = 3;
     * }
     * ```
     */
    export interface P4KS {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.PS
    }
    export function P4KS$$new(p0: number, p1: string, l: ds.PS): P4KS {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }


    /**
     * ```
     * 
     * message P41 {
     *   required uint32 p0 = 1;
     *   required ds.P1 l = 2;
     * }
     * ```
     */
    export interface P41 {
        /** p0 = 1, required */
        ['1']: number
        /** l = 2, required */
        ['2']: ds.P1
    }
    export function P41$$new(p0: number, l: ds.P1): P41 {
        return {
            '1': p0,
            '2': l
        }
    }

    /**
     * ```
     * 
     * message P44 {
     *   required uint32 p0 = 1;
     *   required ds.P4 l = 2;
     * }
     * ```
     */
    export interface P44 {
        /** p0 = 1, required */
        ['1']: number
        /** l = 2, required */
        ['2']: ds.P4
    }
    export function P44$$new(p0: number, l: ds.P4): P44 {
        return {
            '1': p0,
            '2': l
        }
    }

    /**
     * ```
     * 
     * message P48 {
     *   required uint32 p0 = 1;
     *   required ds.P8 l = 2;
     * }
     * ```
     */
    export interface P48 {
        /** p0 = 1, required */
        ['1']: number
        /** l = 2, required */
        ['2']: ds.P8
    }
    export function P48$$new(p0: number, l: ds.P8): P48 {
        return {
            '1': p0,
            '2': l
        }
    }

    /**
     * ```
     * 
     * message P4D {
     *   required uint32 p0 = 1;
     *   required ds.PD l = 2;
     * }
     * ```
     */
    export interface P4D {
        /** p0 = 1, required */
        ['1']: number
        /** l = 2, required */
        ['2']: ds.PD
    }
    export function P4D$$new(p0: number, l: ds.PD): P4D {
        return {
            '1': p0,
            '2': l
        }
    }

    /**
     * ```
     * 
     * message P4K {
     *   required uint32 p0 = 1;
     *   required ds.PK l = 2;
     * }
     * ```
     */
    export interface P4K {
        /** p0 = 1, required */
        ['1']: number
        /** l = 2, required */
        ['2']: ds.PK
    }
    export function P4K$$new(p0: number, l: ds.PK): P4K {
        return {
            '1': p0,
            '2': l
        }
    }

    /**
     * ```
     * 
     * message P4S {
     *   required uint32 p0 = 1;
     *   required ds.PS l = 2;
     * }
     * ```
     */
    export interface P4S {
        /** p0 = 1, required */
        ['1']: number
        /** l = 2, required */
        ['2']: ds.PS
    }
    export function P4S$$new(p0: number, l: ds.PS): P4S {
        return {
            '1': p0,
            '2': l
        }
    }


    /**
     * ```
     * 
     * message P411 {
     *   required uint32 p0 = 1;
     *   required int8 p1 = 2;
     *   required ds.P1 l = 3;
     * }
     * ```
     */
    export interface P411 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P1
    }
    export function P411$$new(p0: number, p1: number, l: ds.P1): P411 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P414 {
     *   required uint32 p0 = 1;
     *   required int8 p1 = 2;
     *   required ds.P4 l = 3;
     * }
     * ```
     */
    export interface P414 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P4
    }
    export function P414$$new(p0: number, p1: number, l: ds.P4): P414 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P418 {
     *   required uint32 p0 = 1;
     *   required int8 p1 = 2;
     *   required ds.P8 l = 3;
     * }
     * ```
     */
    export interface P418 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P8
    }
    export function P418$$new(p0: number, p1: number, l: ds.P8): P418 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P41D {
     *   required uint32 p0 = 1;
     *   required int8 p1 = 2;
     *   required ds.PD l = 3;
     * }
     * ```
     */
    export interface P41D {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PD
    }
    export function P41D$$new(p0: number, p1: number, l: ds.PD): P41D {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P41K {
     *   required uint32 p0 = 1;
     *   required int8 p1 = 2;
     *   required ds.PK l = 3;
     * }
     * ```
     */
    export interface P41K {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PK
    }
    export function P41K$$new(p0: number, p1: number, l: ds.PK): P41K {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P41S {
     *   required uint32 p0 = 1;
     *   required int8 p1 = 2;
     *   required ds.PS l = 3;
     * }
     * ```
     */
    export interface P41S {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PS
    }
    export function P41S$$new(p0: number, p1: number, l: ds.PS): P41S {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }


    /**
     * ```
     * 
     * message P4441 {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required uint32 p2 = 3;
     *   required ds.P1 l = 4;
     * }
     * ```
     */
    export interface P4441 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** l = 4, required */
        ['4']: ds.P1
    }
    export function P4441$$new(p0: number, p1: number, p2: number, l: ds.P1): P4441 {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        }
    }

    /**
     * ```
     * 
     * message P4444 {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required uint32 p2 = 3;
     *   required ds.P4 l = 4;
     * }
     * ```
     */
    export interface P4444 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** l = 4, required */
        ['4']: ds.P4
    }
    export function P4444$$new(p0: number, p1: number, p2: number, l: ds.P4): P4444 {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        }
    }

    /**
     * ```
     * 
     * message P4448 {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required uint32 p2 = 3;
     *   required ds.P8 l = 4;
     * }
     * ```
     */
    export interface P4448 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** l = 4, required */
        ['4']: ds.P8
    }
    export function P4448$$new(p0: number, p1: number, p2: number, l: ds.P8): P4448 {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        }
    }

    /**
     * ```
     * 
     * message P444D {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required uint32 p2 = 3;
     *   required ds.PD l = 4;
     * }
     * ```
     */
    export interface P444D {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** l = 4, required */
        ['4']: ds.PD
    }
    export function P444D$$new(p0: number, p1: number, p2: number, l: ds.PD): P444D {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        }
    }

    /**
     * ```
     * 
     * message P444K {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required uint32 p2 = 3;
     *   required ds.PK l = 4;
     * }
     * ```
     */
    export interface P444K {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** l = 4, required */
        ['4']: ds.PK
    }
    export function P444K$$new(p0: number, p1: number, p2: number, l: ds.PK): P444K {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        }
    }

    /**
     * ```
     * 
     * message P444S {
     *   required uint32 p0 = 1;
     *   required uint32 p1 = 2;
     *   required uint32 p2 = 3;
     *   required ds.PS l = 4;
     * }
     * ```
     */
    export interface P444S {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** p2 = 3, required */
        ['3']: number
        /** l = 4, required */
        ['4']: ds.PS
    }
    export function P444S$$new(p0: number, p1: number, p2: number, l: ds.PS): P444S {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        }
    }


    /**
     * ```
     * 
     * message P4S1 {
     *   required uint32 p0 = 1;
     *   required string p1 = 2;
     *   required ds.P1 l = 3;
     * }
     * ```
     */
    export interface P4S1 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.P1
    }
    export function P4S1$$new(p0: number, p1: string, l: ds.P1): P4S1 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P4S4 {
     *   required uint32 p0 = 1;
     *   required string p1 = 2;
     *   required ds.P4 l = 3;
     * }
     * ```
     */
    export interface P4S4 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.P4
    }
    export function P4S4$$new(p0: number, p1: string, l: ds.P4): P4S4 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P4S8 {
     *   required uint32 p0 = 1;
     *   required string p1 = 2;
     *   required ds.P8 l = 3;
     * }
     * ```
     */
    export interface P4S8 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.P8
    }
    export function P4S8$$new(p0: number, p1: string, l: ds.P8): P4S8 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P4SD {
     *   required uint32 p0 = 1;
     *   required string p1 = 2;
     *   required ds.PD l = 3;
     * }
     * ```
     */
    export interface P4SD {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.PD
    }
    export function P4SD$$new(p0: number, p1: string, l: ds.PD): P4SD {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P4SK {
     *   required uint32 p0 = 1;
     *   required string p1 = 2;
     *   required ds.PK l = 3;
     * }
     * ```
     */
    export interface P4SK {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.PK
    }
    export function P4SK$$new(p0: number, p1: string, l: ds.PK): P4SK {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P4SS {
     *   required uint32 p0 = 1;
     *   required string p1 = 2;
     *   required ds.PS l = 3;
     * }
     * ```
     */
    export interface P4SS {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.PS
    }
    export function P4SS$$new(p0: number, p1: string, l: ds.PS): P4SS {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }



}

