// Generated by fbsgen from p/ds/prk/pk
export var pk;
(function (pk) {
    function PKK1$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PKK1$$new = PKK1$$new;
    function PKK4$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PKK4$$new = PKK4$$new;
    function PKK8$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PKK8$$new = PKK8$$new;
    function PKKD$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PKKD$$new = PKKD$$new;
    function PKKK$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PKKK$$new = PKKK$$new;
    function PKKS$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PKKS$$new = PKKS$$new;
    function PK41$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PK41$$new = PK41$$new;
    function PK44$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PK44$$new = PK44$$new;
    function PK48$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PK48$$new = PK48$$new;
    function PK4D$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PK4D$$new = PK4D$$new;
    function PK4K$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PK4K$$new = PK4K$$new;
    function PK4S$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PK4S$$new = PK4S$$new;
    function PK1111$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    pk.PK1111$$new = PK1111$$new;
    function PK1114$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    pk.PK1114$$new = PK1114$$new;
    function PK1118$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    pk.PK1118$$new = PK1118$$new;
    function PK111D$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    pk.PK111D$$new = PK111D$$new;
    function PK111K$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    pk.PK111K$$new = PK111K$$new;
    function PK111S$$new(p0, p1, p2, p3, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': p3,
            '5': l
        };
    }
    pk.PK111S$$new = PK111S$$new;
    function PK11$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PK11$$new = PK11$$new;
    function PK14$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PK14$$new = PK14$$new;
    function PK18$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PK18$$new = PK18$$new;
    function PK1D$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PK1D$$new = PK1D$$new;
    function PK1K$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PK1K$$new = PK1K$$new;
    function PK1S$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PK1S$$new = PK1S$$new;
    function PKS1$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PKS1$$new = PKS1$$new;
    function PKS4$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PKS4$$new = PKS4$$new;
    function PKS8$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PKS8$$new = PKS8$$new;
    function PKSD$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PKSD$$new = PKSD$$new;
    function PKSK$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PKSK$$new = PKSK$$new;
    function PKSS$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PKSS$$new = PKSS$$new;
    function PKD1$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PKD1$$new = PKD1$$new;
    function PKD4$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PKD4$$new = PKD4$$new;
    function PKD8$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PKD8$$new = PKD8$$new;
    function PKDD$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PKDD$$new = PKDD$$new;
    function PKDK$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PKDK$$new = PKDK$$new;
    function PKDS$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PKDS$$new = PKDS$$new;
    function PK1$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    pk.PK1$$new = PK1$$new;
    function PK4$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    pk.PK4$$new = PK4$$new;
    function PK8$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    pk.PK8$$new = PK8$$new;
    function PKD$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    pk.PKD$$new = PKD$$new;
    function PKK$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    pk.PKK$$new = PKK$$new;
    function PKS$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    pk.PKS$$new = PKS$$new;
    function PK111$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    pk.PK111$$new = PK111$$new;
    function PK114$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    pk.PK114$$new = PK114$$new;
    function PK118$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    pk.PK118$$new = PK118$$new;
    function PK11D$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    pk.PK11D$$new = PK11D$$new;
    function PK11K$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    pk.PK11K$$new = PK11K$$new;
    function PK11S$$new(p0, p1, p2, l) {
        return {
            '1': p0,
            '2': p1,
            '3': p2,
            '4': l
        };
    }
    pk.PK11S$$new = PK11S$$new;
    function PK81$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PK81$$new = PK81$$new;
    function PK84$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PK84$$new = PK84$$new;
    function PK88$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PK88$$new = PK88$$new;
    function PK8D$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PK8D$$new = PK8D$$new;
    function PK8K$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PK8K$$new = PK8K$$new;
    function PK8S$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pk.PK8S$$new = PK8S$$new;
})(pk || (pk = {}));
//# sourceMappingURL=index.js.map