// Generated by fbsgen from p/ds/prk/pd
export var pd;
(function (pd) {
    function PD1$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    pd.PD1$$new = PD1$$new;
    function PD4$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    pd.PD4$$new = PD4$$new;
    function PD8$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    pd.PD8$$new = PD8$$new;
    function PDD$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    pd.PDD$$new = PDD$$new;
    function PDK$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    pd.PDK$$new = PDK$$new;
    function PDS$$new(p0, l) {
        return {
            '1': p0,
            '2': l
        };
    }
    pd.PDS$$new = PDS$$new;
    function PDD1$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PDD1$$new = PDD1$$new;
    function PDD4$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PDD4$$new = PDD4$$new;
    function PDD8$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PDD8$$new = PDD8$$new;
    function PDDD$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PDDD$$new = PDDD$$new;
    function PDDK$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PDDK$$new = PDDK$$new;
    function PDDS$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PDDS$$new = PDDS$$new;
    function PD81$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PD81$$new = PD81$$new;
    function PD84$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PD84$$new = PD84$$new;
    function PD88$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PD88$$new = PD88$$new;
    function PD8D$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PD8D$$new = PD8D$$new;
    function PD8K$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PD8K$$new = PD8K$$new;
    function PD8S$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PD8S$$new = PD8S$$new;
    function PDK1$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PDK1$$new = PDK1$$new;
    function PDK4$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PDK4$$new = PDK4$$new;
    function PDK8$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PDK8$$new = PDK8$$new;
    function PDKD$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PDKD$$new = PDKD$$new;
    function PDKK$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PDKK$$new = PDKK$$new;
    function PDKS$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PDKS$$new = PDKS$$new;
    function PD41$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PD41$$new = PD41$$new;
    function PD44$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PD44$$new = PD44$$new;
    function PD48$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PD48$$new = PD48$$new;
    function PD4D$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PD4D$$new = PD4D$$new;
    function PD4K$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PD4K$$new = PD4K$$new;
    function PD4S$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PD4S$$new = PD4S$$new;
    function PDS1$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PDS1$$new = PDS1$$new;
    function PDS4$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PDS4$$new = PDS4$$new;
    function PDS8$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PDS8$$new = PDS8$$new;
    function PDSD$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PDSD$$new = PDSD$$new;
    function PDSK$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PDSK$$new = PDSK$$new;
    function PDSS$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PDSS$$new = PDSS$$new;
    function PD11$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PD11$$new = PD11$$new;
    function PD14$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PD14$$new = PD14$$new;
    function PD18$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PD18$$new = PD18$$new;
    function PD1D$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PD1D$$new = PD1D$$new;
    function PD1K$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PD1K$$new = PD1K$$new;
    function PD1S$$new(p0, p1, l) {
        return {
            '1': p0,
            '2': p1,
            '3': l
        };
    }
    pd.PD1S$$new = PD1S$$new;
})(pd || (pd = {}));
//# sourceMappingURL=index.js.map