// Generated by fbsgen from p/ds/prk/p8

import { ds } from '../../'

export namespace p8 {
    /**
     * ```
     * 
     * message P881 {
     *   required uint64 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.P1 l = 3;
     * }
     * ```
     */
    export interface P881 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P1
    }
    export function P881$$new(p0: number, p1: number, l: ds.P1): P881 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P884 {
     *   required uint64 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.P4 l = 3;
     * }
     * ```
     */
    export interface P884 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P4
    }
    export function P884$$new(p0: number, p1: number, l: ds.P4): P884 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P888 {
     *   required uint64 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.P8 l = 3;
     * }
     * ```
     */
    export interface P888 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P8
    }
    export function P888$$new(p0: number, p1: number, l: ds.P8): P888 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P88D {
     *   required uint64 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.PD l = 3;
     * }
     * ```
     */
    export interface P88D {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PD
    }
    export function P88D$$new(p0: number, p1: number, l: ds.PD): P88D {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P88K {
     *   required uint64 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.PK l = 3;
     * }
     * ```
     */
    export interface P88K {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PK
    }
    export function P88K$$new(p0: number, p1: number, l: ds.PK): P88K {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P88S {
     *   required uint64 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.PS l = 3;
     * }
     * ```
     */
    export interface P88S {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PS
    }
    export function P88S$$new(p0: number, p1: number, l: ds.PS): P88S {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }


    /**
     * ```
     * 
     * message P811 {
     *   required uint64 p0 = 1;
     *   required int8 p1 = 2;
     *   required ds.P1 l = 3;
     * }
     * ```
     */
    export interface P811 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P1
    }
    export function P811$$new(p0: number, p1: number, l: ds.P1): P811 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P814 {
     *   required uint64 p0 = 1;
     *   required int8 p1 = 2;
     *   required ds.P4 l = 3;
     * }
     * ```
     */
    export interface P814 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P4
    }
    export function P814$$new(p0: number, p1: number, l: ds.P4): P814 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P818 {
     *   required uint64 p0 = 1;
     *   required int8 p1 = 2;
     *   required ds.P8 l = 3;
     * }
     * ```
     */
    export interface P818 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P8
    }
    export function P818$$new(p0: number, p1: number, l: ds.P8): P818 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P81D {
     *   required uint64 p0 = 1;
     *   required int8 p1 = 2;
     *   required ds.PD l = 3;
     * }
     * ```
     */
    export interface P81D {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PD
    }
    export function P81D$$new(p0: number, p1: number, l: ds.PD): P81D {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P81K {
     *   required uint64 p0 = 1;
     *   required int8 p1 = 2;
     *   required ds.PK l = 3;
     * }
     * ```
     */
    export interface P81K {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PK
    }
    export function P81K$$new(p0: number, p1: number, l: ds.PK): P81K {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P81S {
     *   required uint64 p0 = 1;
     *   required int8 p1 = 2;
     *   required ds.PS l = 3;
     * }
     * ```
     */
    export interface P81S {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PS
    }
    export function P81S$$new(p0: number, p1: number, l: ds.PS): P81S {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }


    /**
     * ```
     * 
     * message P841 {
     *   required uint64 p0 = 1;
     *   required uint32 p1 = 2;
     *   required ds.P1 l = 3;
     * }
     * ```
     */
    export interface P841 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P1
    }
    export function P841$$new(p0: number, p1: number, l: ds.P1): P841 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P844 {
     *   required uint64 p0 = 1;
     *   required uint32 p1 = 2;
     *   required ds.P4 l = 3;
     * }
     * ```
     */
    export interface P844 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P4
    }
    export function P844$$new(p0: number, p1: number, l: ds.P4): P844 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P848 {
     *   required uint64 p0 = 1;
     *   required uint32 p1 = 2;
     *   required ds.P8 l = 3;
     * }
     * ```
     */
    export interface P848 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P8
    }
    export function P848$$new(p0: number, p1: number, l: ds.P8): P848 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P84D {
     *   required uint64 p0 = 1;
     *   required uint32 p1 = 2;
     *   required ds.PD l = 3;
     * }
     * ```
     */
    export interface P84D {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PD
    }
    export function P84D$$new(p0: number, p1: number, l: ds.PD): P84D {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P84K {
     *   required uint64 p0 = 1;
     *   required uint32 p1 = 2;
     *   required ds.PK l = 3;
     * }
     * ```
     */
    export interface P84K {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PK
    }
    export function P84K$$new(p0: number, p1: number, l: ds.PK): P84K {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P84S {
     *   required uint64 p0 = 1;
     *   required uint32 p1 = 2;
     *   required ds.PS l = 3;
     * }
     * ```
     */
    export interface P84S {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PS
    }
    export function P84S$$new(p0: number, p1: number, l: ds.PS): P84S {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }


    /**
     * ```
     * 
     * message P81 {
     *   required uint64 p0 = 1;
     *   required ds.P1 l = 2;
     * }
     * ```
     */
    export interface P81 {
        /** p0 = 1, required */
        ['1']: number
        /** l = 2, required */
        ['2']: ds.P1
    }
    export function P81$$new(p0: number, l: ds.P1): P81 {
        return {
            '1': p0,
            '2': l
        }
    }

    /**
     * ```
     * 
     * message P84 {
     *   required uint64 p0 = 1;
     *   required ds.P4 l = 2;
     * }
     * ```
     */
    export interface P84 {
        /** p0 = 1, required */
        ['1']: number
        /** l = 2, required */
        ['2']: ds.P4
    }
    export function P84$$new(p0: number, l: ds.P4): P84 {
        return {
            '1': p0,
            '2': l
        }
    }

    /**
     * ```
     * 
     * message P88 {
     *   required uint64 p0 = 1;
     *   required ds.P8 l = 2;
     * }
     * ```
     */
    export interface P88 {
        /** p0 = 1, required */
        ['1']: number
        /** l = 2, required */
        ['2']: ds.P8
    }
    export function P88$$new(p0: number, l: ds.P8): P88 {
        return {
            '1': p0,
            '2': l
        }
    }

    /**
     * ```
     * 
     * message P8D {
     *   required uint64 p0 = 1;
     *   required ds.PD l = 2;
     * }
     * ```
     */
    export interface P8D {
        /** p0 = 1, required */
        ['1']: number
        /** l = 2, required */
        ['2']: ds.PD
    }
    export function P8D$$new(p0: number, l: ds.PD): P8D {
        return {
            '1': p0,
            '2': l
        }
    }

    /**
     * ```
     * 
     * message P8K {
     *   required uint64 p0 = 1;
     *   required ds.PK l = 2;
     * }
     * ```
     */
    export interface P8K {
        /** p0 = 1, required */
        ['1']: number
        /** l = 2, required */
        ['2']: ds.PK
    }
    export function P8K$$new(p0: number, l: ds.PK): P8K {
        return {
            '1': p0,
            '2': l
        }
    }

    /**
     * ```
     * 
     * message P8S {
     *   required uint64 p0 = 1;
     *   required ds.PS l = 2;
     * }
     * ```
     */
    export interface P8S {
        /** p0 = 1, required */
        ['1']: number
        /** l = 2, required */
        ['2']: ds.PS
    }
    export function P8S$$new(p0: number, l: ds.PS): P8S {
        return {
            '1': p0,
            '2': l
        }
    }


    /**
     * ```
     * 
     * message P8S1 {
     *   required uint64 p0 = 1;
     *   required string p1 = 2;
     *   required ds.P1 l = 3;
     * }
     * ```
     */
    export interface P8S1 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.P1
    }
    export function P8S1$$new(p0: number, p1: string, l: ds.P1): P8S1 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P8S4 {
     *   required uint64 p0 = 1;
     *   required string p1 = 2;
     *   required ds.P4 l = 3;
     * }
     * ```
     */
    export interface P8S4 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.P4
    }
    export function P8S4$$new(p0: number, p1: string, l: ds.P4): P8S4 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P8S8 {
     *   required uint64 p0 = 1;
     *   required string p1 = 2;
     *   required ds.P8 l = 3;
     * }
     * ```
     */
    export interface P8S8 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.P8
    }
    export function P8S8$$new(p0: number, p1: string, l: ds.P8): P8S8 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P8SD {
     *   required uint64 p0 = 1;
     *   required string p1 = 2;
     *   required ds.PD l = 3;
     * }
     * ```
     */
    export interface P8SD {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.PD
    }
    export function P8SD$$new(p0: number, p1: string, l: ds.PD): P8SD {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P8SK {
     *   required uint64 p0 = 1;
     *   required string p1 = 2;
     *   required ds.PK l = 3;
     * }
     * ```
     */
    export interface P8SK {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.PK
    }
    export function P8SK$$new(p0: number, p1: string, l: ds.PK): P8SK {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P8SS {
     *   required uint64 p0 = 1;
     *   required string p1 = 2;
     *   required ds.PS l = 3;
     * }
     * ```
     */
    export interface P8SS {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.PS
    }
    export function P8SS$$new(p0: number, p1: string, l: ds.PS): P8SS {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }


    /**
     * ```
     * 
     * message P8D1 {
     *   required uint64 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.P1 l = 3;
     * }
     * ```
     */
    export interface P8D1 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P1
    }
    export function P8D1$$new(p0: number, p1: number, l: ds.P1): P8D1 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P8D4 {
     *   required uint64 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.P4 l = 3;
     * }
     * ```
     */
    export interface P8D4 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P4
    }
    export function P8D4$$new(p0: number, p1: number, l: ds.P4): P8D4 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P8D8 {
     *   required uint64 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.P8 l = 3;
     * }
     * ```
     */
    export interface P8D8 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.P8
    }
    export function P8D8$$new(p0: number, p1: number, l: ds.P8): P8D8 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P8DD {
     *   required uint64 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.PD l = 3;
     * }
     * ```
     */
    export interface P8DD {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PD
    }
    export function P8DD$$new(p0: number, p1: number, l: ds.PD): P8DD {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P8DK {
     *   required uint64 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.PK l = 3;
     * }
     * ```
     */
    export interface P8DK {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PK
    }
    export function P8DK$$new(p0: number, p1: number, l: ds.PK): P8DK {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P8DS {
     *   required uint64 p0 = 1;
     *   required uint64 p1 = 2;
     *   required ds.PS l = 3;
     * }
     * ```
     */
    export interface P8DS {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: number
        /** l = 3, required */
        ['3']: ds.PS
    }
    export function P8DS$$new(p0: number, p1: number, l: ds.PS): P8DS {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }


    /**
     * ```
     * 
     * message P8K1 {
     *   required uint64 p0 = 1;
     *   required bytes p1 = 2;
     *   required ds.P1 l = 3;
     * }
     * ```
     */
    export interface P8K1 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.P1
    }
    export function P8K1$$new(p0: number, p1: string, l: ds.P1): P8K1 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P8K4 {
     *   required uint64 p0 = 1;
     *   required bytes p1 = 2;
     *   required ds.P4 l = 3;
     * }
     * ```
     */
    export interface P8K4 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.P4
    }
    export function P8K4$$new(p0: number, p1: string, l: ds.P4): P8K4 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P8K8 {
     *   required uint64 p0 = 1;
     *   required bytes p1 = 2;
     *   required ds.P8 l = 3;
     * }
     * ```
     */
    export interface P8K8 {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.P8
    }
    export function P8K8$$new(p0: number, p1: string, l: ds.P8): P8K8 {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P8KD {
     *   required uint64 p0 = 1;
     *   required bytes p1 = 2;
     *   required ds.PD l = 3;
     * }
     * ```
     */
    export interface P8KD {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.PD
    }
    export function P8KD$$new(p0: number, p1: string, l: ds.PD): P8KD {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P8KK {
     *   required uint64 p0 = 1;
     *   required bytes p1 = 2;
     *   required ds.PK l = 3;
     * }
     * ```
     */
    export interface P8KK {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.PK
    }
    export function P8KK$$new(p0: number, p1: string, l: ds.PK): P8KK {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }

    /**
     * ```
     * 
     * message P8KS {
     *   required uint64 p0 = 1;
     *   required bytes p1 = 2;
     *   required ds.PS l = 3;
     * }
     * ```
     */
    export interface P8KS {
        /** p0 = 1, required */
        ['1']: number
        /** p1 = 2, required */
        ['2']: string
        /** l = 3, required */
        ['3']: ds.PS
    }
    export function P8KS$$new(p0: number, p1: string, l: ds.PS): P8KS {
        return {
            '1': p0,
            '2': p1,
            '3': l
        }
    }



}

